### PR TITLE
Update wsldl version to 20100500

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by smorimoto** [comment]
You must merge #3 first.

**Comment by smorimoto** [comment]
The deployment seems to have somehow failed.

**Comment by am11** [comment]
Thanks for the headsup. TravisCI is getting slower by day (job waited for over half an hour..), then for some reason token is expired which I created last year and haven't revoked.

Anyways, I have now switched CI plan to GitHub Actions, which provides seamless artifacts upload mechanics (using `hub(1)`).

New releases are published smoothly in three minutes:
VoidWSL: https://github.com/am11/VoidWSL/releases/tag/20102701
VoidMuslWSL: https://github.com/am11/VoidMuslWSL/releases/tag/20102701

**Comment by smorimoto** [comment]
Yeah, I agree with you. I think that's a pretty good idea.

**Comment by smorimoto** [comment]
Anyway! Thank you for your efforts on these!

**Pull request merged**
